[grid_world]
width = 16
height = 9
entity_count = 3
[grid_world.energy]
energy_capacity=10
initial_energy=10
[grid_world.agent_location]
x = 10
y = 5

[agent]
discount_rate = 0.9
stopping_epsilon = 0.0001
learning_rate = 0.1
sample_count = 100
exploration_ratio = 0.5

[gui]
appearance_mode = "dark"
color_theme = "blue"
initial_size = "800x600"