[grid_world]
width = 8
height = 5
entity_count = 3
[grid_world.agent_location]
x = 3
y = 2

[agent]
discount_rate = 0.9
[agent.value_iteration]
sample_count = 100
stopping_epsilon = 0.0001
[agent.q_learning]
learning_rate = 0.8
initial_optimism = 50.0
replay_queue_length = 10
[agent.q_learning.epsilon_greedy]
initial_exploration_ratio = 0.7
decay_rate = 0.9
[agent.q_learning.upper_confidence_bound]
exploration_bias = 2.0
[agent.q_learning.mf_bpi]
kbar=1
ensemble_size=50
[gui]
appearance_mode = "dark"
color_theme = "blue"
[gui.initial_size]
width = 800
height = 600