files: ^code/

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: bash -c "cd code; poetry run isort src"
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: bash -c "cd code; poetry run black src"
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: bash -c "cd code; poetry run flake8 src"
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: bash -c "cd code; poetry run mypy"
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: bash -c "cd code; poetry run pytest"
        types: [python]

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: bash -c "cd code; poetry run pytest --cov -cov-fail-under=80"
        types: [python]
        pass_filenames: false
      
      - id: gen-docs
        name: "generate docs"
        stages: [push]
        language: system
        entry: bash -c "cd code; poetry run mkdocs build"
        types: [python]
        pass_filenames: false