[grid_world]
width = 16
height = 9
entity_count = 5
[grid_world.energy]
energy_capacity=10
initial_energy=10
[grid_world.agent_location]
x = 10
y = 10


[gui]
theme_style = "Dark"
primary_palette = "DeepPurple"
grid_view_background_hue=800