site_name: "Reinforcement Learning App"
theme:
  name: material
docs_dir: scripts/static_docs
site_dir: docs
plugins:
- search
- gen-files:
    scripts:
      - scripts/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [.src]
