[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Cougar Tasker <cougartasker@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"
pytest = "^7.4.3"
black = "^23.11.0"
numpy = "^1.26.1"
kivy = "^2.2.1"

[tool.poetry.scripts]
main = "src.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
